### ISSUE TITLE
add review schedule/deadline to Card

### ISSUE THREAD

**Issue by jethrokuan** [CS2103JAN2018-W09-B4/main#25]

**Comment by PukiPuki** [comment]
Add to Card:
- nextReview:Calendar
- day:int

Add Scheduler class:
- updateReview(card, 0..2)
- getTodayReviewList()

**Comment by jethrokuan** [comment]
1. Will you not be interested in the ease factor entered in previous reviews? I think SM uses this. maybe store `ArrayList<reviewDate, easeFactor>`? 

2. What happens when you miss your review date?

3. I don't see the need for a scheduler class. Just need 1 static method to compute the next Review date, given a current Card.

4. getReviewList(d) -> returns list of cards due for review that has date before `d`. This should go into the Card class.

**Comment by jethrokuan** [comment]
Closed with #82
