### ISSUE TITLE
change MainWindow to display "Card Packs", with Cards in the side window

### ISSUE THREAD

**Issue by jethrokuan** [CS2103JAN2018-W09-B4/main#52]

**Comment by yong-jie** [comment]
@jethrokuan is this equivalent to "replace PersonListPanel with CardListPanel"?

**Comment by jethrokuan** [comment]
@yong-jie cardListPanel would have to go into the side window, the left panel is where the user would select the list of cards to review. That's not implemented yet, will need to wait for #41 to be pushed out, and more.

**Comment by jethrokuan** [comment]
This is resolved with #56
